// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49qFnG0Oj0gtDZM53ZzAD3dswpgZAPCg',
    appId: '1:609478977380:web:3e5c9a6855be08e3c6bc71',
    messagingSenderId: '609478977380',
    projectId: 'book-control-3e024',
    authDomain: 'book-control-3e024.firebaseapp.com',
    databaseURL: 'https://book-control-3e024-default-rtdb.firebaseio.com',
    storageBucket: 'book-control-3e024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtBG2vNY0dIPK6JxRVmxAVvryTTKu4bV8',
    appId: '1:609478977380:android:d6aa6b39353e49bbc6bc71',
    messagingSenderId: '609478977380',
    projectId: 'book-control-3e024',
    databaseURL: 'https://book-control-3e024-default-rtdb.firebaseio.com',
    storageBucket: 'book-control-3e024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5du6vOhaj9gkgMCzBgeahjC6hTc1QZ3w',
    appId: '1:609478977380:ios:c902c62b48258560c6bc71',
    messagingSenderId: '609478977380',
    projectId: 'book-control-3e024',
    databaseURL: 'https://book-control-3e024-default-rtdb.firebaseio.com',
    storageBucket: 'book-control-3e024.appspot.com',
    iosClientId: '609478977380-sdt7p750bd4q495oudtu6npngvufvig5.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksApp',
  );
}
